//! Runtime configuration.
//!
//! The file is generated by Terraform (`terraform/files/config.toml.tftpl`) and
//! delivered to the instance by the deploy step. It is never edited by hand and
//! never committed — it holds live S3 secret keys and the database password.
//!
//! Two sources of truth, deliberately split:
//!
//! * **Postgres** is authoritative for *which users exist* and which bucket each
//!   one owns (`users.bucket`).
//! * **This file** only answers *how to reach a bucket*.
//!
//! So adding a user is a Terraform change (bucket + credential) plus a database
//! row, and a mismatch between the two surfaces as a startup error rather than a
//! confusing failure the first time someone opens their mail.

use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

/// Where the deploy step writes the file.
const DEFAULT_PATH: &str = "/etc/email-archiver/config.toml";

/// Overrides the path, for local development against the real buckets.
const PATH_ENV: &str = "EMAIL_ARCHIVER_CONFIG";

#[derive(Deserialize)]
pub struct Config {
    pub database: Database,
    pub s3: S3,
    /// Source mailboxes to ingest from, keyed by address.
    ///
    /// Same split as `s3.credentials`: Postgres is authoritative for which
    /// accounts exist (`accounts.address`); this only says how to log in to
    /// one. An account in the database with no entry here simply is not
    /// ingested, and says so.
    #[serde(default)]
    pub sources: HashMap<String, Source>,
}

/// How to reach one source mailbox.
#[derive(Deserialize)]
pub struct Source {
    pub host: String,
    #[serde(default = "default_imaps_port")]
    pub port: u16,
    pub username: String,
    /// Password or app password. Gmail (XOAUTH2) is not supported yet — see
    /// ARCHIVE-PLAN.md 3.3; the generic-IMAP accounts come first deliberately.
    pub password: String,
}

fn default_imaps_port() -> u16 {
    993
}

#[derive(Deserialize)]
pub struct Database {
    pub url: String,
}

#[derive(Deserialize)]
pub struct S3 {
    pub endpoint: String,
    pub region: String,
    /// Keyed by bucket name, matching `users.bucket` in Postgres.
    #[serde(default)]
    pub credentials: HashMap<String, Credentials>,
}

#[derive(Deserialize, Clone)]
pub struct Credentials {
    pub access_key: String,
    pub secret_key: String,
}

impl Config {
    /// Load from `$EMAIL_ARCHIVER_CONFIG`, else the deploy location.
    pub fn load() -> Result<Self> {
        let path: PathBuf = std::env::var_os(PATH_ENV)
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(DEFAULT_PATH));
        Self::load_from(&path)
    }

    pub fn load_from(path: &Path) -> Result<Self> {
        let raw = std::fs::read_to_string(path).with_context(|| {
            format!(
                "reading config from {}\n\nGenerate it with:\n  \
                 cd terraform && terraform output -raw archiver_config > config.toml\n\
                 then point {PATH_ENV} at it.",
                path.display()
            )
        })?;
        let config: Config = toml::from_str(&raw)
            .with_context(|| format!("parsing {}", path.display()))?;
        config.validate()?;
        Ok(config)
    }

    fn validate(&self) -> Result<()> {
        anyhow::ensure!(!self.database.url.is_empty(), "database.url is empty");
        anyhow::ensure!(!self.s3.endpoint.is_empty(), "s3.endpoint is empty");
        Ok(())
    }

    /// How to log in to a source mailbox, by address.
    ///
    /// Reached via `accounts.address`, so a miss means the database knows about
    /// an account the config has no credentials for.
    pub fn source(&self, address: &str) -> Result<&Source> {
        self.sources.get(address).with_context(|| {
            format!(
                "no source credentials configured for {address:?}. \
                 Add it to `source_accounts` in secrets.tfvars and re-run `terraform apply`."
            )
        })
    }

    /// Credentials for a bucket, with an error that names the likely cause.
    ///
    /// Reached via `users.bucket`, so a miss means the database and the
    /// Terraform-generated config disagree about who exists.
    pub fn credentials_for(&self, bucket: &str) -> Result<&Credentials> {
        self.s3.credentials.get(bucket).with_context(|| {
            format!(
                "no S3 credentials configured for bucket {bucket:?}. \
                 A user in Postgres references it but the generated config does not. \
                 Add them to terraform.tfvars `users` and re-run `terraform apply`."
            )
        })
    }
}

/// Redacting `Debug`, so a config can be logged or included in an error chain
/// without leaking secret keys or the database password.
impl fmt::Debug for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Config")
            .field("database.url", &redact_url(&self.database.url))
            .field("s3.endpoint", &self.s3.endpoint)
            .field("s3.region", &self.s3.region)
            .field("s3.buckets", &self.s3.credentials.keys().collect::<Vec<_>>())
            .field("sources", &self.sources.keys().collect::<Vec<_>>())
            .finish()
    }
}

impl fmt::Debug for Source {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Source")
            .field("host", &self.host)
            .field("port", &self.port)
            .field("username", &self.username)
            .field("password", &"<redacted>")
            .finish()
    }
}

impl fmt::Debug for Credentials {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Credentials")
            .field("access_key", &self.access_key)
            .field("secret_key", &"<redacted>")
            .finish()
    }
}

/// `postgres://user:secret@host/db` -> `postgres://user:<redacted>@host/db`
fn redact_url(url: &str) -> String {
    match (url.find("://"), url.find('@')) {
        (Some(scheme), Some(at)) if at > scheme => {
            let creds = &url[scheme + 3..at];
            match creds.find(':') {
                Some(colon) => format!(
                    "{}{}:<redacted>{}",
                    &url[..scheme + 3],
                    &creds[..colon],
                    &url[at..]
                ),
                None => url.to_string(),
            }
        }
        _ => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redacts_password_in_url() {
        assert_eq!(
            redact_url("postgres://gern:hunter2@db.example:5432/archive"),
            "postgres://gern:<redacted>@db.example:5432/archive"
        );
    }

    #[test]
    fn leaves_passwordless_url_alone() {
        let url = "postgres://db.example:5432/archive";
        assert_eq!(redact_url(url), url);
    }

    #[test]
    fn debug_does_not_leak_secrets() {
        let config: Config = toml::from_str(
            r#"
            [database]
            url = "postgres://gern:hunter2@db.example:5432/archive"
            [s3]
            endpoint = "https://s3.example"
            region = "bhs"
            [s3.credentials."ken-twoducks-ca"]
            access_key = "AKIA"
            secret_key = "topsecret"
            "#,
        )
        .unwrap();

        let rendered = format!("{config:?}");
        assert!(!rendered.contains("hunter2"), "password leaked: {rendered}");
        assert!(!rendered.contains("topsecret"), "secret key leaked: {rendered}");
        assert!(rendered.contains("ken-twoducks-ca"));

        let creds = config.credentials_for("ken-twoducks-ca").unwrap();
        assert!(!format!("{creds:?}").contains("topsecret"));
    }

    #[test]
    fn missing_bucket_names_the_cause() {
        let config: Config = toml::from_str(
            r#"
            [database]
            url = "postgres://x@y/archive"
            [s3]
            endpoint = "https://s3.example"
            region = "bhs"
            "#,
        )
        .unwrap();

        let err = config.credentials_for("absent-bucket").unwrap_err().to_string();
        assert!(err.contains("absent-bucket"), "{err}");
    }
}
