//! Runtime configuration.
//!
//! The file is generated by Terraform (`terraform/files/config.toml.tftpl`) and
//! delivered to the instance by the deploy step. It is never edited by hand and
//! never committed — it holds live S3 secret keys and the database password.
//!
//! Two sources of truth, deliberately split:
//!
//! * **Postgres** is authoritative for *which users exist* and which bucket each
//!   one owns (`users.bucket`).
//! * **This file** only answers *how to reach a bucket*.
//!
//! So adding a user is a Terraform change (bucket + credential) plus a database
//! row, and a mismatch between the two surfaces as a startup error rather than a
//! confusing failure the first time someone opens their mail.

use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

/// Where the deploy step writes the file.
const DEFAULT_PATH: &str = "/etc/email-archiver/config.toml";

/// Overrides the path, for local development against the real buckets.
const PATH_ENV: &str = "EMAIL_ARCHIVER_CONFIG";

#[derive(Deserialize)]
pub struct Config {
    pub database: Database,
    pub s3: S3,
    /// Base64 32-byte key for encrypting source mailbox passwords.
    ///
    /// Deliberately here and not in the database: a key stored alongside what
    /// it protects is decoration. See src/secrets.rs.
    pub encryption_key: String,
    #[serde(default)]
    pub ingest: Ingest,
    #[serde(default)]
    pub tls: Tls,
    #[serde(default)]
    pub gmail: Gmail,
}

/// Google Workspace ingest. Absent unless there are Workspace mailboxes.
#[derive(Deserialize, Default)]
pub struct Gmail {
    /// Path to the service account JSON key, with domain-wide delegation
    /// granted for `https://mail.google.com/`. See src/gmail.rs for the setup.
    ///
    /// One key serves every mailbox in the domain, so this is global rather
    /// than per-account. A second Workspace domain would need a second key and
    /// a change here.
    pub service_account_key: Option<String>,
}

/// How ingest authenticates to a source mailbox.
///
/// Kept as an enum rather than an optional token beside an optional password,
/// so a source cannot be half-configured with both or neither.
pub enum Auth {
    /// Generic IMAP. Decrypted in memory only; never written back anywhere.
    Password(String),
    /// Google Workspace, via a service account impersonating the mailbox. The
    /// token is minted per connection and lives about an hour, so unlike a
    /// password there is nothing here worth persisting.
    XOAuth2 { token: String },
}

/// TLS for the IMAP listener.
///
/// Certificates come from files, not an in-process ACME client — certbot or
/// similar writes them and renews on its own schedule. See src/tls.rs.
#[derive(Deserialize, Default)]
pub struct Tls {
    /// Full-chain certificate, PEM. Absent means serve plaintext.
    pub cert_path: Option<String>,
    /// Private key, PEM.
    pub key_path: Option<String>,
}

impl Tls {
    /// Both paths, or neither. A half-configured TLS section is almost
    /// certainly a mistake, and silently serving plaintext because one line was
    /// missing is exactly the failure worth being loud about.
    pub fn paths(&self) -> Result<Option<(&str, &str)>> {
        match (&self.cert_path, &self.key_path) {
            (Some(c), Some(k)) => Ok(Some((c.as_str(), k.as_str()))),
            (None, None) => Ok(None),
            _ => anyhow::bail!(
                "tls.cert_path and tls.key_path must be set together — one without the \
                 other would silently serve plaintext"
            ),
        }
    }
}

/// How to reach one source mailbox. Loaded from the database, not config.
pub struct Source {
    pub host: String,
    pub port: u16,
    pub username: String,
    /// How to prove who we are to this server.
    pub auth: Auth,

    /// Accept any server certificate for this source, including expired,
    /// self-signed, or wrong-hostname ones.
    ///
    /// **This disables authentication of the server entirely.** The connection
    /// is still encrypted, but nothing proves you are talking to the intended
    /// host — an attacker on the path could present their own certificate,
    /// take the password, and hand back whatever they liked as your mail.
    ///
    /// Per-source, so one server with a stale certificate does not quietly
    /// weaken every other connection.
    pub allow_invalid_certs: bool,
}

#[derive(Deserialize)]
pub struct Database {
    pub url: String,
    /// Connection pool ceiling.
    ///
    /// This cluster is shared with the game services and we connect as the same
    /// role, so the pool is a courtesy limit as much as a performance knob.
    /// Should be at least `ingest.concurrency`, or ingest tasks queue waiting
    /// for a connection.
    #[serde(default = "default_max_connections")]
    pub max_connections: u32,
}

fn default_max_connections() -> u32 {
    8
}

#[derive(Deserialize)]
pub struct Ingest {
    /// Messages processed in parallel within one fetched batch.
    ///
    /// Each message costs several round trips (S3 put, a few Postgres
    /// statements, S3 manifest put), and those dominate wall-clock — the work
    /// is latency-bound, not CPU-bound, so this can exceed the core count.
    /// Raising it past what the source IMAP server or the database pool will
    /// take just moves the queue.
    #[serde(default = "default_concurrency")]
    pub concurrency: usize,
}

fn default_concurrency() -> usize {
    8
}

impl Default for Ingest {
    fn default() -> Self {
        Self {
            concurrency: default_concurrency(),
        }
    }
}

#[derive(Deserialize)]
pub struct S3 {
    pub endpoint: String,
    pub region: String,
    /// Keyed by bucket name, matching `users.bucket` in Postgres.
    #[serde(default)]
    pub credentials: HashMap<String, Credentials>,
}

#[derive(Deserialize, Clone)]
pub struct Credentials {
    pub access_key: String,
    pub secret_key: String,
}

impl Config {
    /// Load from `$EMAIL_ARCHIVER_CONFIG`, else the deploy location.
    pub fn load() -> Result<Self> {
        let path: PathBuf = std::env::var_os(PATH_ENV)
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(DEFAULT_PATH));
        Self::load_from(&path)
    }

    pub fn load_from(path: &Path) -> Result<Self> {
        let raw = std::fs::read_to_string(path).with_context(|| {
            format!(
                "reading config from {}\n\nGenerate it with:\n  \
                 cd terraform && terraform output -raw archiver_config > config.toml\n\
                 then point {PATH_ENV} at it.",
                path.display()
            )
        })?;
        let config: Config =
            toml::from_str(&raw).with_context(|| format!("parsing {}", path.display()))?;
        config.validate()?;
        Ok(config)
    }

    fn validate(&self) -> Result<()> {
        anyhow::ensure!(!self.database.url.is_empty(), "database.url is empty");
        anyhow::ensure!(!self.s3.endpoint.is_empty(), "s3.endpoint is empty");
        anyhow::ensure!(
            self.ingest.concurrency >= 1,
            "ingest.concurrency must be at least 1"
        );
        anyhow::ensure!(
            !self.encryption_key.is_empty(),
            "encryption_key is empty. Generate one with: email-archiver generate-key"
        );
        if (self.database.max_connections as usize) < self.ingest.concurrency {
            eprintln!(
                "warning: ingest.concurrency ({}) exceeds database.max_connections ({});                  ingest tasks will queue on the connection pool",
                self.ingest.concurrency, self.database.max_connections
            );
        }
        Ok(())
    }

    pub fn key(&self) -> Result<crate::secrets::SecretKey> {
        crate::secrets::SecretKey::from_base64(&self.encryption_key)
    }

    /// Credentials for a bucket, with an error that names the likely cause.
    ///
    /// Reached via `users.bucket`, so a miss means the database and the
    /// Terraform-generated config disagree about who exists.
    pub fn credentials_for(&self, bucket: &str) -> Result<&Credentials> {
        self.s3.credentials.get(bucket).with_context(|| {
            format!(
                "no S3 credentials configured for bucket {bucket:?}. \
                 A user in Postgres references it but the generated config does not. \
                 Add them to terraform.tfvars `users` and re-run `terraform apply`."
            )
        })
    }
}

/// Redacting `Debug`, so a config can be logged or included in an error chain
/// without leaking secret keys or the database password.
impl fmt::Debug for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Config")
            .field("database.url", &redact_url(&self.database.url))
            .field("s3.endpoint", &self.s3.endpoint)
            .field("s3.region", &self.s3.region)
            .field(
                "s3.buckets",
                &self.s3.credentials.keys().collect::<Vec<_>>(),
            )
            .field("encryption_key", &"<redacted>")
            .finish()
    }
}

#[allow(dead_code)]
impl fmt::Debug for Source {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Source")
            .field("host", &self.host)
            .field("port", &self.port)
            .field("username", &self.username)
            .field("password", &"<redacted>")
            .finish()
    }
}

impl fmt::Debug for Credentials {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Credentials")
            .field("access_key", &self.access_key)
            .field("secret_key", &"<redacted>")
            .finish()
    }
}

/// `postgres://user:secret@host/db` -> `postgres://user:<redacted>@host/db`
fn redact_url(url: &str) -> String {
    match (url.find("://"), url.find('@')) {
        (Some(scheme), Some(at)) if at > scheme => {
            let creds = &url[scheme + 3..at];
            match creds.find(':') {
                Some(colon) => format!(
                    "{}{}:<redacted>{}",
                    &url[..scheme + 3],
                    &creds[..colon],
                    &url[at..]
                ),
                None => url.to_string(),
            }
        }
        _ => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redacts_password_in_url() {
        assert_eq!(
            redact_url("postgres://gern:hunter2@db.example:5432/archive"),
            "postgres://gern:<redacted>@db.example:5432/archive"
        );
    }

    #[test]
    fn leaves_passwordless_url_alone() {
        let url = "postgres://db.example:5432/archive";
        assert_eq!(redact_url(url), url);
    }

    #[test]
    fn debug_does_not_leak_secrets() {
        let config: Config = toml::from_str(
            r#"
            encryption_key = "c3VwZXJzZWNyZXRrZXltYXRlcmlhbDMyYnl0ZXNsb25n"
            [database]
            url = "postgres://gern:hunter2@db.example:5432/archive"
            [s3]
            endpoint = "https://s3.example"
            region = "bhs"
            [s3.credentials."ken-twoducks-ca"]
            access_key = "AKIA"
            secret_key = "topsecret"
            "#,
        )
        .unwrap();

        let rendered = format!("{config:?}");
        assert!(!rendered.contains("hunter2"), "password leaked: {rendered}");
        assert!(
            !rendered.contains("topsecret"),
            "secret key leaked: {rendered}"
        );
        // The encryption key must never appear either — it is the one secret
        // whose exposure makes every stored source password readable.
        assert!(
            !rendered.contains("c3VwZXJzZWNyZXQ"),
            "encryption key leaked: {rendered}"
        );
        assert!(rendered.contains("ken-twoducks-ca"));

        let creds = config.credentials_for("ken-twoducks-ca").unwrap();
        assert!(!format!("{creds:?}").contains("topsecret"));
    }

    #[test]
    fn missing_bucket_names_the_cause() {
        let config: Config = toml::from_str(
            r#"
            encryption_key = "c3VwZXJzZWNyZXRrZXltYXRlcmlhbDMyYnl0ZXNsb25n"
            [database]
            url = "postgres://x@y/archive"
            [s3]
            endpoint = "https://s3.example"
            region = "bhs"
            "#,
        )
        .unwrap();

        let err = config
            .credentials_for("absent-bucket")
            .unwrap_err()
            .to_string();
        assert!(err.contains("absent-bucket"), "{err}");
    }
}
